wallpaper {
    monitor = eDP-1
    path = /home/aditya/dotfiles/wallpapers/pink2.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/aditya/dotfiles/wallpapers/pink2.png
    fit_mode = cover
}

splash = true
ipc = true
